<!DOCTYPE html>
<html>
<head>
    <title>Booking Report</title>
    <style>
        /* Define your styles for the PDF report */
        body {
            font-family: Arial, sans-serif;
        }
        .report-header {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-header h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        .report-header p {
            font-size: 16px;
            margin: 0;
        }
        .booking-table {
            width: 100%;
            border-collapse: collapse;
        }
        .booking-table th,
        .booking-table td {
            padding: 8px;
            border: 1px solid #ccc;
        }
        .booking-table th {
            background-color: #f2f2f2;
        }
        .booking-table td img {
            max-width: 50px;
            max-height: 50px;
            border-radius: 50%;
        }
        .report-footer {
            text-align: right;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <h1>Mentor Report</h1>
        <p>Date: {{ now()->format('Y-m-d') }}</p>
    </div>

    <table class="booking-table">
        <thead>
            <tr>
                <th>Booking</th>
                <th>Mentor</th>
                <th>Mentee</th>
                <th>Mentor Email</th>
                <th>Date</th>
                <th>Status</th>
                <th>Earnings</th>
            </tr>
        </thead>
        <tbody>
            {{$i=1}}
            @foreach($bookings as $booking)
                <tr>
                    <td>{{$i++}}</td>
                    <td>
                        {{-- <img src="{{ $booking->mentor->photo }}" alt="Mentor Photo"> --}}
                        {{ $booking->mentor->fname }} {{ $booking->mentor->lname }}
                    </td>
                    <td>{{$booking->mentee->name}}</td>
                    <td>{{ $booking->mentor->email }}</td>
                    <td>{{ $booking->created_at }}</td>
                    <td>{{ $booking->status }}</td>
                    <td>{{ $booking->total_fees }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6">Total Earnings</td>
                <td>{{ $totalEarnings }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="report-footer">
        Generated By: {{ Auth::guard('admin')->user()->name }}
    </div>
</body>
</html>
